In [1]:
num=2.5

In [2]:
type(num)

float

In [3]:
num=5

In [4]:
type(num)

int

In [5]:
n=1+3j

In [6]:
type(n)

complex

In [7]:
a=8.5

In [8]:
b=int(a)

In [9]:
b

8

In [10]:
c=float(b)

In [11]:
c

8.0

In [12]:
d=complex(b,c)

In [13]:
d

(8+8j)

In [26]:
a=7
b=5
a>b

True

In [27]:
a=55
b=77
bool(a>b)

False

In [29]:
int(True)

1

In [1]:
type(bool)

type

In [30]:
int(False)

0

In [31]:
a=[11,23,44]

In [32]:
type(a)

list

In [33]:
a=(11,33,44)

In [34]:
type(a)

tuple

In [35]:
a={11,22,33}

In [36]:
type(a)

set

In [37]:
b="Zoya"

In [38]:
type(b)

str

In [39]:
b='zoya'

In [40]:
type(b)

str

In [41]:
range(10)

range(0, 10)

In [42]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [46]:
list(range(2,11,2))

[2, 4, 6, 8, 10]

In [47]:
type(range(10))

range

In [51]:
d={"Zoya":"vivo","Ananya":"Oppo"}

In [52]:
d.keys()

dict_keys(['Zoya', 'Ananya'])

In [53]:
d.values()

dict_values(['vivo', 'Oppo'])

In [54]:
d['Zoya']

'vivo'

In [55]:
d.get('Ananya')

'Oppo'

In [56]:
a=4
b=7

In [57]:
a+b

11

In [58]:
a-b

-3

In [59]:
a/b

0.5714285714285714

In [60]:
a=a+7

In [61]:
a

11

In [63]:
a+=2

In [64]:
a

13

In [65]:
b*=2

In [66]:
b

14

In [67]:
x,y=2,6

In [68]:
x

2

In [69]:
y

6

In [70]:
-x

-2

In [71]:
x

2

In [72]:
x=-x

In [73]:
x

-2

In [74]:
x>y

False

In [75]:
x<y

True

In [76]:
x==y

False

In [77]:
a,b=5,5

In [78]:
a==b

True

In [79]:
a<=b

True

In [80]:
a!=b

False

In [81]:
a=6
b=8

In [84]:
a<8 and b>5

True

In [85]:
a<8 and b<5

False

In [86]:
a<8 or b<5

True

In [87]:
x=True

In [88]:
not x

False

In [89]:
bin(25)

'0b11001'

In [90]:
0b001

1

In [91]:
oct(25)

'0o31'

In [92]:
hex(25)

'0x19'

In [93]:
0x11

17

In [94]:
0xb

11

In [95]:
bin(31)

'0b11111'

In [96]:
bin(52)

'0b110100'

In [97]:
bin(65)

'0b1000001'

In [99]:
0b110011010

410

In [101]:
~12

-13

In [102]:
~0

-1

In [104]:
~0b00001100

-13

In [106]:
~0b11110011

-244

In [107]:
bin(45)

'0b101101'

In [108]:
bin(121)

'0b1111001'

In [109]:
~45

-46

In [110]:
bin(46)

'0b101110'

In [111]:
bin(-46)

'-0b101110'

In [112]:
14&23

6

In [113]:
12|13

13

In [114]:
25&44

8

In [115]:
bin(25)

'0b11001'

In [116]:
bin(30)

'0b11110'

In [117]:
12^13

1

In [118]:
25^30

7

In [119]:
10<<2

40

In [120]:
10>>2

2

In [6]:
x=input("Enter the first number")
a=int(x)
y=input("Enter the second number")
b=int(y)
z=a+b

Enter the first number5
Enter the second number5


In [7]:
x=int(input("Enter the first number"))
y=int(input("Enter the second number"))
print(x+y)


Enter the first number4
Enter the second number5
9


In [9]:
ch=input("Enter a char")
print(ch[0])

Enter a charjj
j


In [10]:
ch=input("Enter a char")[0]
print(ch)

Enter a charhhh
h


In [12]:
result=eval(input("Enter the expr"))
print (result)

Enter the expr5+2*3
11


In [13]:
a=int(input("Enter the number"))
print(a*a*a)

Enter the number5
125


In [14]:
lst=[11,23,55,66,77]

In [15]:
lst

[11, 23, 55, 66, 77]

In [16]:
lst[0]

11

In [17]:
lst[-1]

77

In [19]:
lst[1:]

[23, 55, 66, 77]

In [20]:
string=['zoya','anu','ayesha']


In [21]:
string

['zoya', 'anu', 'ayesha']

In [22]:
value=[22,'zoya',2.3]

In [25]:
lil=[lst,string]

In [26]:
lil

[[11, 23, 55, 66, 77], ['zoya', 'anu', 'ayesha']]

In [27]:
lst.append(5)

In [28]:
lst

[11, 23, 55, 66, 77, 5]

In [29]:
lst.insert(1,66)

In [30]:
lst

[11, 66, 23, 55, 66, 77, 5]

In [32]:
lst.pop(0)

11

In [33]:
lst.pop()

77

In [42]:
del lst[2:]

In [39]:
lst

[]

In [40]:
del lst[1:]

In [41]:
lst

[]

In [44]:
lst.extend([11,22,33])

In [45]:
lst

[11, 22, 33]

In [46]:
min(lst)

11

In [48]:
max(lst)

33

In [49]:
sum(lst)

66

In [50]:
lst.sort()

In [51]:
lst

[11, 22, 33]

In [53]:
tup=(21,22,23,24)

In [54]:
tup

(21, 22, 23, 24)

In [55]:
tup[0]

21

In [60]:
tup.count(1)

0

In [63]:
se={44,55,22,33}

In [64]:
se

{22, 33, 44, 55}

In [65]:
s={88,44,55,99,88,11}

In [66]:
s

{11, 44, 55, 88, 99}

In [67]:
s.add(5)

In [68]:
s

{5, 11, 44, 55, 88, 99}

In [70]:
s.clear()

In [71]:
s

set()

In [72]:
sample={2:'zoya',1:'anu',3:'allu'}

In [73]:
sample

{2: 'zoya', 1: 'anu', 3: 'allu'}

In [74]:
sample[2]

'zoya'

In [75]:
sample.get(1)

'anu'

In [76]:
sample.get(4)

In [77]:
sample.get(4,'Not Found')

'Not Found'

In [78]:
key=['Zoya','laksh','anni']

In [79]:
values=['python','java','c']

In [81]:
sample=dict(zip(key,value))

In [82]:
sample

{'Zoya': 22, 'laksh': 'zoya', 'anni': 2.3}

In [83]:
sample['moana']='js'

In [84]:
sample

{'Zoya': 22, 'laksh': 'zoya', 'anni': 2.3, 'moana': 'js'}

In [85]:
del sample['moana']

In [86]:
sample

{'Zoya': 22, 'laksh': 'zoya', 'anni': 2.3}

In [87]:
prog={'js':'Atom','cs':'vs','python':['pycharm','sublime'],'java':['netbeans','jee']}

In [89]:
prog['java']

['netbeans', 'jee']

In [2]:
if True:
    print("I'm A Student")

I'm A Student


In [3]:
if False:
    print("I'm Tired")
print("Bye")

Bye


In [6]:
a=8
if(a%2==0):
    print("Even")
else:
    print("odd")

Even


In [9]:
a=1
b=a%2
if(b==0):
    print("Even")
if(b==1):
    print("odd")

odd


In [11]:
a=5
if(a%2==0):
    print("Even")
    if(a>5):
        print("Great")
    else:
        print("Not great")
else:
    print("odd")

odd


In [14]:
a=int(input("Enter the number"))
if(a==1):
    print("One")
if(a==2):
    print("Two")
if(a==3):
    print("Three")

Enter the number3
Three


In [13]:
a=int(input("Enter the number"))
if(a==1):
    print("One")
elif(a==2):
    print("Two")
elif(a==3):
    print("Three")

Enter the number3
Three


In [16]:
a=int(input("Enter the number"))
if(a<0):
    print("It's a negative number")
else:
    print("it's a positive number")

Enter the number5
it's a positive number


In [2]:
a=int(input("Enter the first number"))
b=int(input("Enter the second number"))
c=int(input("Enter the third number"))
if(a>b and a>c):
    print("A is greatest")
elif(b>a and b>c):
    print("B is greatest")
else:
    print("C is greatest")

Enter the first number5
Enter the second number8
Enter the third number7
B is greatest


In [21]:
print("Zoya")
print("Zoya")


Zoya
Zoya


In [31]:
i=1
while(i<=6):
    print("Zoya",i)
    i=i+1

Zoya 1
Zoya 2
Zoya 3
Zoya 4
Zoya 5
Zoya 6


In [4]:
i=1

while(i<=5):
    print("Tata",end="")
    j=1
    while(j<=4):
        print("Titan",end="")
        j=j+1
    i=i+1
    print()

TataTitanTitanTitanTitan
TataTitanTitanTitanTitan
TataTitanTitanTitanTitan
TataTitanTitanTitanTitan
TataTitanTitanTitanTitan


In [2]:
a=1
while(a<101):
    print(a)
    a=a+1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [ ]:
a=1
while(a<100):
     print(a)
    if(a%3==0 & a%5==0):
        break;
    else:
        continue;
    
   
    a=a+1
    

In [3]:
a=["Zoya",2,2.3]
for i in a:
    print(i)

Zoya
2
2.3


In [2]:
a

['Zoya', 2, 2.3]

In [4]:
a="ZOYA"
for i in a:
    print(i)

Z
O
Y
A


In [5]:
for i in [2,9,0,7]:
    print(i)

2
9
0
7


In [8]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [9]:
for i in range(0,10,2):
    print(i)

0
2
4
6
8


In [10]:
for i in range(20,10,-2):
    print(i)

20
18
16
14
12


In [11]:
for i in range(1,21):
    if(i%5!=0):
        print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19


In [13]:
for i in range(1,500):
    print(pow(i,2))

1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
484
529
576
625
676
729
784
841
900
961
1024
1089
1156
1225
1296
1369
1444
1521
1600
1681
1764
1849
1936
2025
2116
2209
2304
2401
2500
2601
2704
2809
2916
3025
3136
3249
3364
3481
3600
3721
3844
3969
4096
4225
4356
4489
4624
4761
4900
5041
5184
5329
5476
5625
5776
5929
6084
6241
6400
6561
6724
6889
7056
7225
7396
7569
7744
7921
8100
8281
8464
8649
8836
9025
9216
9409
9604
9801
10000
10201
10404
10609
10816
11025
11236
11449
11664
11881
12100
12321
12544
12769
12996
13225
13456
13689
13924
14161
14400
14641
14884
15129
15376
15625
15876
16129
16384
16641
16900
17161
17424
17689
17956
18225
18496
18769
19044
19321
19600
19881
20164
20449
20736
21025
21316
21609
21904
22201
22500
22801
23104
23409
23716
24025
24336
24649
24964
25281
25600
25921
26244
26569
26896
27225
27556
27889
28224
28561
28900
29241
29584
29929
30276
30625
30976
31329
31684
32041
32400
32761
33124
33489
33856
34225
34596
34969
35344
35721
36100
36

In [6]:
av=5
a=int(input("How many candies you want"))
i=1
while i<=a:
    if i>av:
        print("out of stock")
        break;
    print("Candy")
    i+=1
print("Sorry")

How many candies you want7
Candy
Candy
Candy
Candy
Candy
out of stock
Sorry


In [8]:
for i in range(1,101):
    if i%3==0 or i%5==0:
        continue
    print(i)


1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49
52
53
56
58
59
61
62
64
67
68
71
73
74
76
77
79
82
83
86
88
89
91
92
94
97
98


In [9]:
for i in range(1,101):
    if i%3==0 and i%5==0:
        continue
    print(i)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
16
17
18
19
20
21
22
23
24
25
26
27
28
29
31
32
33
34
35
36
37
38
39
40
41
42
43
44
46
47
48
49
50
51
52
53
54
55
56
57
58
59
61
62
63
64
65
66
67
68
69
70
71
72
73
74
76
77
78
79
80
81
82
83
84
85
86
87
88
89
91
92
93
94
95
96
97
98
99
100


In [10]:
for i in range(1,101):
    if i%2!=0:
        pass
    else:
        print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [11]:
a=int(input("Enter a number"))
if(a%2==0):
    print("Not a prime number")
else:
    print("Prime number")

Enter a number7
Prime number


In [12]:
import array as arr
arr.array('i',[5,9,7])

array('i', [5, 9, 7])

In [16]:
from array import *
value=array('i',[5,7,9])
print(value)

array('i', [5, 7, 9])


In [18]:
from array import *
value=array('i',[5,7,9])
print(value.typecode)

i


In [21]:
from array import *
value=array('i',[5,7,9])
value.reverse()
print(value)

array('i', [9, 7, 5])


In [24]:
from array import *
value=array('i',[5,7,9])
for i in range(3):
    print(value[i])

5
7
9


In [27]:
from array import *
value=array('i',[5,7,9,8,6])
for e in value:
    print(e)

5
7
9
8
6


In [29]:
from array import *
value=array('u',['a','i','b'])
print(value)

array('u', 'aib')


In [31]:
from array import *
value=array('i',[5,7,9])
new=array(value.typecode,(a*a for a in value))
for e in new:
    print(e)
    


25
49
81


In [32]:
from array import *
value=array('i',[5,7,9])
new=array(value.typecode,(a*a for a in value))
i=0
while i<len(new):
    print(new[i])
    i+=1

25
49
81


In [33]:
for i in range(5):
    if i==3:
        continue
    print("Hello",i)

Hello 0
Hello 1
Hello 2
Hello 4


In [34]:
for i in range(5):
    if i==3:
        break
    print("Hello",i)

Hello 0
Hello 1
Hello 2


In [36]:
for i in range(5):
    if i==3:
        pass
    print("Hello",i)

Hello 0
Hello 1
Hello 2
Hello 3
Hello 4


In [41]:
for i in range(4):    
    for j in range (5):
        print("# ",end="")
    print( )

# # # # # 
# # # # # 
# # # # # 
# # # # # 


In [44]:
for i in range(4):    
    for j in range (i+1):
        print("# ",end="")
    print( )

# 
# # 
# # # 
# # # # 


In [46]:
for i in range(4):    
    for j in range (4-i):
        print("# ",end="")
    print( )

# # # # 
# # # 
# # 
# 


In [50]:
for i in range(4):    
    for j in range (0,i):
        print("1 2 3 4 ",end="")
    print( )


1 2 3 4 
1 2 3 4 1 2 3 4 
1 2 3 4 1 2 3 4 1 2 3 4 


In [53]:
nums=[5,7,9,6]
for num in nums:
    if num%5==0:
        print(num)

5


In [55]:
nums=[1,2,3,4]
for num in nums:
    if num%5==0:
        print(num)
        break
else:
    print("Not found")

Not found


In [63]:
from array import *
arr=array('i',[])
n=int(input("Enter the length of array"))
for i in range(n):
    x=int(input("Enter the next value"))
    arr.append(x)
print(arr)
val=int(input("Enter the value to search"))
k=0
for e in arr:
    if e==val:
        print(k)
        break
    k+=1
    print(arr.index(val))


Enter the length of array2
Enter the next value1
Enter the next value2
array('i', [1, 2])
Enter the value to search3


In [65]:
from numpy import *
arr=array([1,2,3,4,5,6])
print(arr.dtype)
print(arr)

int32
[1 2 3 4 5 6]


In [68]:
from numpy import *
arr=linspace(0,15)

print(arr)

[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


In [70]:
from numpy import *
arr=arange(1,10,2)

print(arr)

[1 3 5 7 9]


In [74]:
from numpy import *
arr=logspace(1,40,5)
print('%.2f'%arr[4])

10000000000000000303786028427003666890752.00


In [76]:
from numpy import*
arr=zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [77]:
from numpy import*
arr=ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [79]:
from numpy import*
arr=ones(5,int)
print(arr)

[1 1 1 1 1]


In [81]:
from numpy import *
arr =array([1,2,3,4,5])
arr=arr+5
print(arr)

[ 6  7  8  9 10]


In [84]:
from numpy import *
arr1 =array([1,2,3,4,5])
arr2 =array([1,2,3,4,5])
arr3=arr1+arr2
print(arr)

[ 6  7  8  9 10]


In [87]:
from numpy import *
arr =array([1,2,3,4,5])

print(sum(arr))
* *we can find log,min,max,sort,sqrt

15


In [89]:
from numpy import *
arr =array([1,2,3,4,5])

print(min(arr))

1


In [91]:
from numpy import *
arr1 =array([1,2,3,4,5])
arr2 =array([1,2,3,4,5])
print(concatenate([arr1,arr2]))

[1 2 3 4 5 1 2 3 4 5]


In [92]:
from numpy import *
arr1 =array([1,2,3,4,5])
arr2=arr1.view()// shallow copy
print(arr1)
print(arr2)

[1 2 3 4 5]
[1 2 3 4 5]


In [93]:
from numpy import *
arr1 =array([1,2,3,4,5])
arr2=arr1.copy()// two different array
arr1[1]=7
print(arr1)
print(arr2)

[1 7 3 4 5]
[1 2 3 4 5]


In [94]:
from numpy import *
arr1 =array([1,2,3,4,5])//alaising same memory address
arr2=arr1
print(arr1)
print(arr2)

[1 2 3 4 5]
[1 2 3 4 5]


In [96]:
from numpy import *
arr1=array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [99]:
from numpy import *
arr1=array([[1,2,3],[4,5,6]])
print(arr1.dtype)

int32


In [100]:
from numpy import *
arr1=array([[1,2,3],[4,5,6]])
print(arr1.ndim)

2


In [101]:
from numpy import *
arr1=array([[1,2,3],[4,5,6]])
print(arr1.shape)// number of row aND COLOUMN

(2, 3)


In [102]:
from numpy import *
arr1=array([[1,2,3],[4,5,6]])
print(arr1.size)

6


In [103]:
from numpy import *
arr1=array([[1,2,3],[4,5,6]])
arr2=arr1.flatten()
print(arr2)

[1 2 3 4 5 6]


In [114]:
from numpy import *
arr1=array([[1,2,3,4,5,6],[4,5,6,7,8,9]])
arr2=arr1.flatten()
arr3=arr2.reshape(3,4)
print(arr3)

[[1 2 3 4]
 [5 6 4 5]
 [6 7 8 9]]


In [115]:
from numpy import *
arr1=array([[1,2,3],[4,5,6]])
m=matrix(arr1)
print(m)

[[1 2 3]
 [4 5 6]]


In [118]:
from numpy import *
m=matrix('1,2,3;4,5,6;7,8,9')
print(diagonal(m))

[1 5 9]


In [120]:
from numpy import *
m=matrix('1,2,3;4,5,6;7,8,9')
print(m.min())

1


In [122]:
from numpy import *
m1=matrix('1,2,3;4,5,6;7,8,9')
m2=matrix('1,2,3;4,5,6;4,8,9')
m3=m1*m2
print(m3)


[[ 21  36  42]
 [ 48  81  96]
 [ 75 126 150]]


In [1]:
def greek():
    print("Hello")
    print("Good morning")

In [2]:
greek()

Hello
Good morning


In [4]:
def add(x,y):
    c=x+y
    return c
add(5,4)
    
    

9

In [5]:
def add_sub(x,y):
    c=x+y
    d=x-y
    return c,d
add_sub(5,4)
    

(9, 1)

In [7]:
def modify(a):
    a=8
    print (a)
x=10
modify(10)
print(x)

    

8
10


In [11]:
def update(lst):
    print(id(lst))

    lst[1]=25
    print(id(lst))
    print("x",lst)
lst=[10,20,30,40]
print(id(lst))
update(lst)
print("lst",lst)

1524875782400
1524875782400
1524875782400
x [10, 25, 30, 40]
lst [10, 25, 30, 40]


In [12]:
def add(a,b):
    c=a+b
    print(c)
add(5,6)
    

11


In [13]:
def person(name,age):
    print(name)
    print(age)
person('Zoya',19)

Zoya
19


In [14]:
def person(name,age):
    print(name)
    print(age)
person(name='Zoya',age=19)

Zoya
19


In [15]:
def person(name,age=18):
    print(name)
    print(age)
person(name='Zoya')

Zoya
18


In [16]:
def sum(a,b):
    c=a+b
    print(c)
sum(4,8)

12


In [17]:
def sum(a,*b):
    c=a
    for i in b:
        c=c+i
    print(c)
sum(1,44,55,66,7)

173


In [19]:
def person(name,**data):
    print(name)
    print(data)
person('zoya',age=19,city='shimoga',mobno=778866889)

zoya
{'age': 19, 'city': 'shimoga', 'mobno': 778866889}


In [25]:
def person(name,**data):
    print(name)
    for i,j in data.items():
        print(i,j)
person('zoya',age=19,city='shimoga',mobno=778866889)

zoya
age 19
city shimoga
mobno 778866889


In [30]:
a=10
def adad():
    a=15
    print("in func",a)
adad()
print("Outside",a)

in func 15
Outside 10


In [31]:
a=10
def adad():
    global a
    a=15
    print("in func",a)
adad()
print("Outside",a)

in func 15
Outside 15


In [35]:
a=10
print(id(a))
def adad():
    a=8
    x=globals()['a']
    print(id(x))
    print("in func",a)
    globals()['a']=15
adad()
print("Outside",a)

1524796228112
1524796228112
in func 8
Outside 15


In [39]:
def count(lst):
    even=0
    odd=0
    for i in lst:
        if(i%2==0):
            even+=1
        else:
            odd+=1
    return even,odd
lst=[1,2,3,4,5,6,7,8,9]
even, odd=count(lst)
print("Even: {} and odd : {}".format(even,odd))

Even: 4 and odd : 5


In [41]:
def fib(n):
    a=0
    b=1
    print(a)
    print(b)
    for i in range(2,n):
        c=a+b
        a=b
        b=c
        print(a+b)
fib(5)

0
1
2
3
5


In [43]:
def fib(n):
    a=0
    b=1
    if(n==1):
        print(a)
    else:
        print(a)
        print(b)
    for i in range(2,n):
        c=a+b
        a=b
        b=c
        print(a+b)
fib(1)

0


In [44]:
def fact(n):
    f=1
    for i in range(1,n+1):
        f=f*i
    return f
x=5
result=fact(x)
print(result)
        

120


In [46]:

import sys
print(sys.getrecursionlimit())
def greek():
    print("Hello")
    greek()
    

3000


In [47]:
def fact(n):
    if (n==0):
        return 1
    return n*fact(n-1)
result=fact(5)
print(result)

120


In [48]:
def square(a):
    return a*a
result=square(5)
print(result)

25


In [51]:
f=lambda a:a*a
result=f(5)
print(result)

25


In [52]:
f=lambda a,b:a+b
result=f(5,6)
print(result)

11


In [55]:
def is_even(n):
    return n%2==0
nums=[3,4,5,6,7,8]
evens=list(filter(is_even,nums))
print(evens)

[4, 6, 8]


In [56]:
nums=[3,4,5,6,7,8]
evens=list(filter(lambda n: n%2==0,nums))
print(evens)

[4, 6, 8]


In [58]:
nums=[3,4,5,6,7,8]
evens=list(filter(lambda n: n%2==0,nums))
double=list(map(lambda n: n*2,evens))
print(evens)
print(double)

[4, 6, 8]
[8, 12, 16]


In [61]:
from functools import reduce
nums=[3,4,5,6,7,8]
evens=list(filter(lambda n: n%2==0,nums))
double=list(map(lambda n: n*2,evens))
sum=reduce(lambda a,b: a+b,double)
print(evens)
print(double)
print(sum)

[4, 6, 8]
[8, 12, 16]
36


In [63]:
def div(a,b):
    print(a/b)
def smart_div(func):
    def inner(a,b):
        if(a<b):
            a,b=b,a
        return func(a,b)
    return inner
div1=smart_div(div)
div1(2,4)

2.0


In [69]:
print(__name__)

__main__


In [8]:
class computer:
    def config(self):
        print("i5, 16gb, 1tb")
com1=computer()
com2=computer()
computer.config(com1)
computer.config(com2)
com1.config()
com2.config()

i5, 16gb, 1tb
i5, 16gb, 1tb
i5, 16gb, 1tb
i5, 16gb, 1tb


In [10]:
class computer:
    def __init__(self):
        print("in init")
    def config(self):
        print("i5, 16gb, 1tb")
com1=computer()
com2=computer()
com1.config()
com2.config()

in init
in init
i5, 16gb, 1tb
i5, 16gb, 1tb


In [12]:
class computer:
    def __init__(self,cpu,ram):
        self.cpu=cpu
        self.ram=ram
        
    def config(self):
        print("config is",self.cpu,self.ram)
com1=computer("i5",16)
com2=computer("Rysen",8)
com1.config()
com2.config()

config is i5 16
config is Rysen 8


In [13]:
class computer:
    pass
c1=computer()
c2=computer()
print(id(c1))
print(id(c2))

2349112832544
2349112826592


In [15]:
class computer:
    def __init__(self):
        self.name="Zoya"
        self.age=19
c1=computer()
c2=computer()
c1.name="Ani"
c1.age=18
print(c1.name)
print(c2.name)
    

Ani
Zoya


In [16]:
class computer:
    def __init__(self):
        self.name="Zoya"
        self.age=19
    def update(self):
        self.age=30
c1=computer()
c2=computer()
c1.name="Ani"
c1.age=18
c1.update()
print(c1.name)
print(c2.name)
    

Ani
Zoya


In [19]:
class computer:
    def __init__(self):
        self.name="Zoya"
        self.age=19
    def update(self):
        self.age=30
    def compare(self,other):
        if(self.age==other.age):
            return True
        else:
            return False
c1=computer()
c2=computer()
if c1.compare(c2):
    print("They are same")

print(c1.name)
print(c2.name)
    

They are same
Zoya
Zoya


In [20]:
class car:
    def __init__(self):
        self.mil=10
        self.comp="BMW"
c1=car()
c2=car()
print(c1.comp,c1.mil)
print(c2.comp,c2.mil)


BMW 10
BMW 10


In [23]:
class car:
    wheels=4
    def __init__(self):
        self.mil=10
        self.comp="BMW"
c1=car()
c2=car()
c1.mil=8
car.wheels=5
print(c1.comp,c1.mil,c1.wheels)
print(c2.comp,c2.mil,c2.wheels)


BMW 8 5
BMW 10 5


In [35]:
class student:
    school="PESItm"
    def __init__(self,m1,m2,m3):
        self.m1=m1
        self.m2=m2
        self.m3=m3
    def avg(self):
        return(self.m1+self.m2+self.m3)/3
    @classmethod
    def getschool(cls):
        return cls.school
    @staticmethod
    def info():
        print("This is student class..in the module")
        
s1=student(11,22,33)
s2=student(22,44,55)
print(s1.avg())
print(s2.avg())
print(student.getschool())
student.info()


22.0
40.333333333333336
PESItm
This is student class..in the module


In [40]:
class student:
    def __init__(self,name,rollno):
        self.name=name
        self.rollno=rollno
        self.lap=self.laptop()
    def show(self):
        print(self.name,self.rollno)
        self.lap.show()
    class laptop:
        def __init__(self):
            self.brand="HP"
            self.cpu="i5"
            self.ram=8
        def show(self):
            print(self.brand,self.cpu,self.ram)
s1=student("Zoya",22)
s2=student("Ani",44)
s1.show()


Zoya 22
HP i5 8


In [48]:
class A:
    def feature1(self):
        print("Feature1 working")
    def feature2(self):
        print("Feature2 working")
class B:
    
     def feature3(self):
        print("Feature3 working")
     def feature4(self):
        print("Feature 4 is working")
    
class C(A,B):
    def feature5(self):
        print("Feature5 working")
    
a1=A()
a1.feature1()
a1.feature2()
b1=B()
c1=C()

    

Feature1 working
Feature2 working


In [80]:
class pycharm:
    def execute(self):
        print("Compilling")
        print("Running")
class myeditor:
    def execute(self):
        print("Spell check")
        print("Convention check")
        print("Compiling")
        print("Running")
class laptop:
    def code(self,ide):
        ide.execute()
ide=myeditor()
lap1=laptop()
lap1.code(ide)

        

Spell check
Convention check
Compiling
Running


In [81]:
print(int.__add__(2,3))

5


In [93]:
class student:
    def __init__(self,m1,m2):
        self.m1=m1
        self.m2=m2
    def __add__(self,other):
        m1=self.m1+other.m1
        m2=self.m2+other.m2
        s3=student(m1,m2)
        return s3

s1=student(77,88)
s2=student(88,77)
s3=s1+s2
print(s3.m1)


165


In [100]:
class student:
    def __init__(self,m1,m2):
        self.m1=m1
        self.m2=m2
    def sum(self,a=None,b=None,c=None):
        s=0
        if a!=None and b!=None and c!=None:
            s=a+b+c
        elif(a!=None and b!=None):
            s=a+b
        else:
            s=a
        return s
s1=student(22,44)
print(s1.sum(5,9))

14


In [101]:
class A:
    def show(self):
        print("in A show")
class B(A):
    pass
a1=B()
a1.show()

in A show


In [104]:
n=[1,2,3,4]
it=iter(n)
print(it.__next__())
print(next(it))
for i in n:
    print(i)

1
2
1
2
3
4


In [114]:
def topten():
    yield 1
    yield 2
    yield 3
values=topten()
print(values.__next__())
for i in values:
    print(i)
    


1
2
3


In [116]:
def topten():
    n=1
    while n<=10:
        sq=n*n
        yield sq
        n+=1
    
values=topten()
for i in values:
    print(i)

1
4
9
16
25
36
49
64
81
100


In [119]:
a=4
b=7
print(a/b)

0.5714285714285714


In [125]:
a=5
b=2
try:
    print("Resource open")
    print(a/b)
    k=int(input("Enter a number"))
    print(k)

except ZeroDivisionError as e:
    print("you cannot divide a numbee by zero",e)
except ValueError as e:
    print("Invalid input")
except Exception as e:
    print("Something went wrong..")
finally:
    print("Resourse closed")

Resource open
2.5
Enter a numberk
Invalid input
Resourse closed


In [127]:
class hello:
    def run(self):
        for i in range(5):
            print("Hello")
class hi:
     def run(self):
        for i in range(5):
            print("Hi")
t1=hello()
t2=hi()
t1.run()
t2.run()
    

Hello
Hello
Hello
Hello
Hello
Hi
Hi
Hi
Hi
Hi


In [131]:
from time import sleep
from threading import *
class hello(Thread):
    def run(self):
        for i in range(5):
            print("Hello")
            sleep(1)
class hi(Thread):
     def run(self):
        for i in range(5):
            print("Hi")
            sleep(1)
t1=hello()
t2=hi()
t1.start()
sleep(0.2)
t2.start()
t1.join()
t2.join()
print("Bye")
    

Hello
Hi
Hello
Hi
Hello
Hi
Hello
Hi
Hello
Hi
Bye
